### ISSUE TITLE
Error while running pod install

### ISSUE THREAD

**Issue by Neelrp12** [the-blue-alliance/the-blue-alliance-ios#84]
Neels-MacBook-Pro-2:~ NeelPatel$ cd /Users/NeelPatel/Downloads/the-blue-alliance-ios-swift/the-blue-alliance-ios
Neels-MacBook-Pro-2:the-blue-alliance-ios NeelPatel$ pod install
[in /Users/NeelPatel/Downloads/the-blue-alliance-ios-swift]
Analyzing dependencies
Fetching podspec for `React` from `js/node_modules/react-native`
[!] No podspec found for `React` in `js/node_modules/react-native`
Neels-MacBook-Pro-2:the-blue-alliance-ios NeelPatel$

**Comment by ZachOrr** [comment]
Have you run `npm install` in the JS folder?

**Comment by Neelrp12** [comment]
I get this.

Neels-MacBook-Pro-2:~ NeelPatel$ cd /Users/NeelPatel/Downloads/the-blue-alliance-ios-swift/js
Neels-MacBook-Pro-2:js NeelPatel$ npm install

module.js:340
    throw err;
          ^
Error: Cannot find module 'child-process-close'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/npm/lib/npm.js:15:1
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:555:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Neels-MacBook-Pro-2:js NeelPatel$

**Comment by ZachOrr** [comment]
Seems to work for me - I'm using npm 5.5.1

**Comment by ZachOrr** [comment]
Also seems to work with the newest version of npm (5.8.0)

**Comment by Neelrp12** [comment]
Can you upload a video of a step by step guide to build this app in Xcode?

**Comment by ZachOrr** [comment]
Update your npm and let me know if you still have issues installing the JS dependencies

**Comment by Neelrp12** [comment]
<img width="1276" alt="screen shot 2018-04-09 at 11 27 02 pm" src="https://user-images.githubusercontent.com/18753423/38534700-8eda6dce-3c4d-11e8-9065-33b5a3bb0d43.png">



what do I do?

**Comment by Neelrp12** [comment]
<img width="1276" alt="screen shot 2018-04-09 at 11 27 02 pm" src="https://user-images.githubusercontent.com/18753423/38534757-e7635dfc-3c4d-11e8-9818-402420482b0c.png">

**Comment by Neelrp12** [comment]
<img width="813" alt="screen shot 2018-04-09 at 11 29 20 pm" src="https://user-images.githubusercontent.com/18753423/38534763-ee6dc984-3c4d-11e8-9788-14dc40526b33.png">

**Comment by Neelrp12** [comment]
Now I am getting this 

<img width="802" alt="screen shot 2018-04-09 at 11 36 10 pm" src="https://user-images.githubusercontent.com/18753423/38534914-dd0ca998-3c4e-11e8-957c-315ef70cb9de.png">

**Comment by ZachOrr** [comment]
You need to open the workspace file generated by Cocoapods `the-blue-alliance-ios.xcworkspace`

**Comment by Neelrp12** [comment]
where is that file

**Comment by Neelrp12** [comment]
I did and I'm getting the same error
